# Generated by Django 4.0.3 on 2022-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_visit_action_remove_visit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='enter_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('S', 'Stay'), ('L', 'Leave')], max_length=1),
        ),
    ]
