# Generated by Django 4.0.3 on 2022-04-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_visit_enter_time_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
