# Generated by Django 4.0.3 on 2022-04-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_visit_exit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='status',
        ),
    ]
